spo:
  reduction: sum
blackbox:
  reduction: sum
  lambd: 0.1
identity:
  reduction: sum
qptl:
  reduction: sum
  tau: 1.0
listLTR:
  reduction: sum
  tau: 1
pairLTR:
  reduction: sum
pointLTR:
  reduction: sum
nce:
  reduction: sum
lodl:
  num_samples: 50000
  sampling: random_hessian
  sampling_std: -1
  quadrank: 20
  quadalpha: 0
  model_type: quad++
  serial: False
  reduction: sum
  num_iters: 100
  losslr: 1e-3
  train_frac: 0.6
  test_frac: 0.2
  patience: 25
  verbose: False
mse:
  reduction: sum
msesum:
  alpha: 0.1
bce:
  reduction: sum
ce:
  reduction: sum
dfl:
  dflalpha: 0.1
  reduction: sum
perturb: 
  reduction: sum