dataset:
  budget: 1
  num_items: 50


models:
  spo:
    reduction: mean
  blackbox:
    reduction: mean
  Identity:
    reduction: mean
  QPTL:
    reduction: mean
  listLTR:
    reduction: mean
  pairLTR:
    reduction: mean
  pointLTR:
    reduction: mean
  nce:
    reduction: mean
  LODL:
    sampling: random
  mse:
    reduction: mean
  msesum:
    alpha: 0.1
  ce:
    reduction: mean
  dfl:
    dflalpha: 0.1