dataset:
  budget: 5
  num_items: 50
  prob_version: gen

models:
  spo:
    reduction: sum
  blackbox:
    reduction: sum
    lambd: 0.1
  identity:
    reduction: sum
  qptl:
    reduction: sum
  listLTR:
    reduction: sum
  pairLTR:
    reduction: sum
  pointLTR:
    reduction: sum
  nce:
    reduction: sum
  lodl:
    sampling: random
    quadrank: 20
    quadalpha: 0
    serial: True
    reduction: sum
  mse:
    reduction: sum
  ce:
    reduction: sum
  dfl:
    dflalpha: 0.1
    reduction: sum
    
solver:
  heuristic:
    kwargs: none