dataset:
  prob_version: gen
  # generate knapsack data
  generate_weight: True
  unit_weight: False
  noise_level: 0
  noise_width: 0.5
  poly_deg: 4
  knapsack_dim: 1
  num_items: 20
  capacity: 100

models:
  spo:
    reduction: sum
  blackbox:
    reduction: sum
    lambd: 0.1
  identity:
    reduction: sum
  qptl:
    reduction: sum
  listLTR:
    reduction: sum
    tau: 1
  pairLTR:
    reduction: sum
  pointLTR:
    reduction: sum
  nce:
    reduction: sum
  lodl:
    sampling: random
    quadrank: 20
    quadalpha: 0
    serial: True
    reduction: sum
  mse:
    reduction: sum
  msesum:
    alpha: 0.1
  ce:
    reduction: sum
  dfl:
    dflalpha: 0.1
    reduction: sum
  perturb: 
    reduction: sum

solver:
  gurobi:
    kwargs: none
