dataset:
  prob_version: gen
  num_features: 5
  noise_width: 0.5
  poly_deg: 4
  knapsack_dim: 1
  num_items: 20
  capacity: 30
  distr: normal
  mean: 0
  var: 1
  

solver:
  gurobi:
    kwargs: None
  qptl:
    kwargs: None
  cvxpy:
    kwargs: None
    