dataset:
  prob_version: gen-ood
  noise_width: 0.5
  poly_deg: 4
  knapsack_dim: 1
  num_items: 20
  capacity: 30
  num_features: 5
  distr: normal
  mean: 10
  var: 10
  mean_val: 5
  var_val: 5
  mean_test: 0
  var_test: 1
  envs:
    env0:
      mean: 1
      var: 1
    env1:
      mean: 2
      var: 1
    env2:
      mean: 4
      var: 1
    env3:
      mean: 8
      var: 1
    env4:
      mean: 16
      var: 1
    env5:
      mean: 32
      var: 1

      
solver:
  gurobi:
    kwargs: None
  qptl:
    kwargs: None
  cvxpy:
    kwargs: None  
    