dataset:
  prob_version: gen-ood
  num_features: 40
  noise_width: 0.2
  poly_deg: 2
  num_nodes: 20
  distance_factor: 1
  type: cluster
  params: 
    num_clusters: 4
    cluster_std: 3
    center_low: 15
    center_high: 55
  type_val:  gaussian
  params_val:
    mean_x: 50
    mean_y: 10
    gaussian_std: 5
  type_test: uniform
  params_test: 
    low: 30
    high: 40
  envs:
    env0:
      type: gaussian
      params:
        mean_x: 40
        mean_y: 20
        gaussian_std: 6
    env1:
      type: explosion
      params: 
        low: 20
        high: 60
        min_eps: 5
        max_eps: 7
        center_low: 37
        center_high: 43
    env2:
      type: uniform
      params: 
        low: 40
        high: 60



solver:
  gurobi:
    kwargs: None
  heuristic:
    kwargs: None