spo:
  reduction: mean
blackbox:
  reduction: mean
  lambd: 0.1
blackboxSolver:
  reduction: mean
  lambd: 0.1  
identity:
  reduction: mean
identitySolver:
  reduction: mean  
qptl:
  reduction: mean
  tau: 1.0
listLTR:
  reduction: mean
  tau: 1
pairLTR:
  reduction: mean
pointLTR:
  reduction: mean
nce:
  reduction: mean
lodl:
  num_samples: 500
  sampling: random_hessian
  sampling_std: -1
  quadrank: 20
  quadalpha: 0
  model_type: weightedmse
  serial: True
  reduction: mean
  num_iters: 100
  losslr: 1e-3
  train_frac: 0.6
  test_frac: 0.2
  patience: 25
  verbose: False
mse:
  reduction: mean
msemean:
  alpha: 0.1
bce:
  reduction: mean
mae:
  reduction: mean
ce:
  reduction: mean
dfl:
  dflalpha: 0.1
  reduction: mean
perturb: 
  reduction: mean
cpLayer:
  reduction: mean